let obj = {
  data: {
    results: [
      {
        id: 1,
        title: 'The Amazing Spider-Man #1',
        description: 'The first issue featuring Peter Parker as Spider-Man.',
        pageCount: 32,
        thumbnail: {
          path: 'https://cdn.kobo.com/book-images/64195770-a73f-4f7c-a005-ff4de60fbf98/1200/1200/False/amazing-spider-man-vol-1',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 3.99 }],
      },
      {
        id: 2,
        title: 'Avengers #1',
        description: "The first assembly of Earth's Mightiest Heroes.",
        pageCount: 40,
        thumbnail: {
          path: 'https://static.wikia.nocookie.net/marveldatabase/images/c/cc/Avengers_Vol_1_1',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 4.99 }],
      },
      {
        id: 3,
        title: 'Iron Man #1',
        description: 'The origin story of Tony Stark becoming Iron Man.',
        pageCount: 38,
        thumbnail: {
          path: 'https://m.media-amazon.com/images/I/61udNZ5VsWL._UF1000,1000_QL80_',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 3.5 }],
      },
      {
        id: 4,
        title: 'Thor #1',
        description: 'Thor wields Mjolnir to defend Asgard and Midgard.',
        pageCount: 36,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/9/70/59c3dade08381/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 4.5 }],
      },
      {
        id: 5,
        title: 'Hulk #1',
        description:
          'Bruce Banner transforms into the Hulk for the first time.',
        pageCount: 32,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/9/a0/59933ea5b5c2e/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 3.99 }],
      },
      {
        id: 6,
        title: 'Black Panther #1',
        description: "T'Challa takes on the mantle of the Black Panther.",
        pageCount: 35,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/7/b0/597799ec72aa9/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 4.99 }],
      },
      {
        id: 7,
        title: 'Doctor Strange #1',
        description:
          'The Sorcerer Supreme begins his journey into the mystic arts.',
        pageCount: 30,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/b/d0/5b3e4ae406c5a/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 3.75 }],
      },
      {
        id: 8,
        title: 'Deadpool #1',
        description: "The beginning of the Merc with a Mouth's adventures.",
        pageCount: 28,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/8/03/6601d3468731f/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 4.25 }],
      },
      {
        id: 9,
        title: 'X-Men #1',
        description: 'Professor X assembles the first team of mutants.',
        pageCount: 40,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/c/f0/589ddfc222e9c/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 5.99 }],
      },
      {
        id: 10,
        title: 'Guardians of the Galaxy #1',
        description: 'A team of misfits comes together to save the universe.',
        pageCount: 38,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/b/70/5b314e1ab2ad7/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 4.99 }],
      },
      {
        id: 11,
        title: 'Fantastic Four #1',
        description: "The origin of Marvel's first family.",
        pageCount: 36,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/6/20/519b7424af23c/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 3.99 }],
      },
      {
        id: 12,
        title: 'Silver Surfer #1',
        description: 'The cosmic wanderer embarks on a new journey.',
        pageCount: 34,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/3/e0/51b63958a75e4/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 4.25 }],
      },
      {
        id: 13,
        title: 'Captain America #1',
        description: 'Steve Rogers takes up the shield for the first time.',
        pageCount: 32,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/3/a0/5991fa03329b7/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 3.5 }],
      },
      {
        id: 14,
        title: 'Daredevil #1',
        description: 'Matt Murdock embraces his alter ego as Daredevil.',
        pageCount: 30,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/7/10/51894efb25f92/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 3.75 }],
      },
      {
        id: 15,
        title: 'The Punisher #1',
        description: 'Frank Castle begins his war on crime.',
        pageCount: 28,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/3/50/5c2537d63c740/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 4.99 }],
      },
      {
        id: 16,
        title: 'Venom #1',
        description: 'Eddie Brock becomes the lethal protector.',
        pageCount: 36,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/8/a0/5aea3123880ca/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 3.99 }],
      },
      {
        id: 17,
        title: 'Infinity Gauntlet #1',
        description: 'Thanos begins his quest for ultimate power.',
        pageCount: 40,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/9/20/51f6911ce3cc3/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 5.99 }],
      },
      {
        id: 18,
        title: 'Secret Wars #1',
        description: 'Heroes and villains are transported to Battleworld.',
        pageCount: 38,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/9/b0/51dee6dd91671/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 4.99 }],
      },
      {
        id: 19,
        title: 'Civil War #1',
        description:
          'The Marvel Universe is split in two over superhero registration.',
        pageCount: 45,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/e/f0/511307b2f1200/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 6.5 }],
      },
      {
        id: 20,
        title: 'House of M #1',
        description: 'Scarlet Witch reshapes reality in this epic event.',
        pageCount: 42,
        thumbnail: {
          path: 'https://cdn.marvel.com/u/prod/marvel/i/mg/3/c0/589b3f23c9324/clean',
          extension: 'jpg',
        },
        textObjects: { languages: 'en' },
        prices: [{ price: 5.75 }],
      },
    ],
  },
};
